### ISSUE TITLE
_ncs.error.Error: access denied (3): access denied

### ISSUE THREAD

**Issue by MitchellMahan** [NSO-developer/ntool#5]
When running ntool_template.py I get an access denied error.

I went to root but get the same error - any ideas? The error output is not very telling for me.

[root@nso-01 ntool_modules]# python3.6 ntool_template.py 

Creating template  type [device] ....

        Searching for existing NSO CLI based network element drivers
Traceback (most recent call last):
  File "ntool_template.py", line 273, in <module>
    main(sys.argv[1:])
  File "ntool_template.py", line 236, in main
    cto.find_ned_ids()
  File "ntool_template.py", line 118, in find_ned_ids
    for pkg in root.ncs__packages.package:
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 1345, in __next__
    return self.next()
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 1361, in next
    k = self._cursor.next()
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maapi.py", line 1381, in next
    key = _tm.maapi.get_next(self.cur)
_ncs.error.Error: access denied (3): access denied

**Comment by djsullivan** [comment]
Hi,
No but I’ll take a look and see what happens. 
-Dan

**Comment by MitchellMahan** [comment]
I added groups=['ncsadmin'] to line 115:

with ncs.maapi.single_read_trans(self.username, 'python', groups=['ncsadmin']) as t:

but now get the following error:

[root@nso-01 ntool_modules]# python3.6 ntool_template.py -u admin

Creating template  type [device] ....

        Searching for existing NSO CLI based network element drivers
Traceback (most recent call last):
  File "ntool_template.py", line 273, in <module>
    main(sys.argv[1:])
  File "ntool_template.py", line 236, in main
    cto.find_ned_ids()
  File "ntool_template.py", line 120, in find_ned_ids
    if comp.ned.cli and comp.ned.cli.ned_id and "cli" in comp.ned.cli.ned_id:
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 471, in __getattr__
    return child.get_value()
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 934, in get_value
    return _yang_to_python(self._cache, self._cs_node)
  File "/opt/ncs/current/src/ncs/pyapi/ncs/maagic.py", line 1945, in _yang_to_python
    return value.val2str(schema_node)
_ncs.error.Error: item has a bad/wrong type (5): Invalid value for type

**Comment by djsullivan** [comment]
Usually, I install this using a local install. Its not really meant for a system install.
